num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
add = num1 + num2
sub = num1 - num2
mul = num1 * num2
div = num1 / num2
print(f"Addition: {num1} + {num2} = {add}")
print(f"Subtraction: {num1} - {num2} = {sub}")
print(f"Multiplication: {num1} * {num2} = {mul}")
print(f"Division: {num1} / {num2} = {div}")
